# Generated by Django 5.1.6 on 2025-03-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_additionalinfo_favorite_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='favorite_genre',
            field=models.CharField(blank=True, choices=[('accion', 'Acción'), ('drama', 'Drama'), ('terror', 'Terror'), ('comedia', 'Comedia'), ('belica', 'Bélica'), ('romantica', 'Romántica'), ('animacion', 'Animación'), ('aventura', 'Aventura'), ('fantasia', 'Fantasía'), ('misterio', 'Misterio'), ('musical', 'Musical'), ('thriller', 'Thriller'), ('ciencia_ficcion', 'Ciencia Ficción'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Género favorito'),
        ),
    ]
