# Generated by Django 5.1.6 on 2025-03-16 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_additionalinfo_favorite_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalinfo',
            old_name='favorite_genre',
            new_name='genero_favorito',
        ),
    ]
