# Generated by Django 5.1.6 on 2025-03-16 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_favorite_genre_additionalinfo_genero_favorito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalinfo',
            old_name='genero_favorito',
            new_name='favorite_genre',
        ),
    ]
