# Generated by Django 5.1.6 on 2025-03-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_movie_rating_alter_movie_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('accion', 'Acción'), ('drama', 'Drama'), ('terror', 'Terror'), ('comedia', 'Comedia'), ('belica', 'Bélica'), ('romantica', 'Romántica'), ('animacion', 'Animación'), ('aventura', 'Aventura'), ('fantasia', 'Fantasía'), ('misterio', 'Misterio'), ('musical', 'Musical'), ('thriller', 'Thriller'), ('ciencia_ficcion', 'Ciencia Ficción'), ('otro', 'Otro')], default='Otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.DateField(),
        ),
    ]
