# Generated by Django 5.1.6 on 2025-03-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alter_movie_genre_alter_movie_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('accion', 'Acción'), ('drama', 'Drama'), ('terror', 'Terror'), ('comedia', 'Comedia'), ('belica', 'Bélica'), ('romantica', 'Romántica'), ('animacion', 'Animación'), ('aventura', 'Aventura'), ('fantasia', 'Fantasía'), ('misterio', 'Misterio'), ('musical', 'Musical'), ('thriller', 'Thriller'), ('ciencia_ficcion', 'Ciencia Ficción'), ('otro', 'Otro')], max_length=20),
        ),
    ]
