# Generated by Django 5.1.6 on 2025-03-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_movie_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
